language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.1
  - DJANGO=https://github.com/django/django/tarball/stable/1.6.x
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install coverage coveralls $DJANGO --use-mirrors

script: coverage run -a setup.py test

matrix:
  exclude:
   - python: 2.6
     env: DJANGO=https://github.com/django/django/tarball/master
   - python: 3.2
     env: DJANGO=Django==1.3.7
   - python: 3.3
     env: DJANGO=Django==1.3.7
   - python: 3.2
     env: DJANGO=Django==1.4.5
   - python: 3.3
     env: DJANGO=Django==1.4.5

after_success: coveralls
